### ISSUE TITLE
Issue to login mobile

### ISSUE THREAD

**Issue by killmasta93** [linagora/Twake#2567]
**Describe the bug**
Issue to logging in on mobile self hosted 

**To Reproduce**
1) change server to my server name
2) tries to login but app crashes 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] samsung galaxy 20fe

**Additional context**
Currently on Desktop application works fine and on web only issue is mobile
Currently i have Twake on docker

```
services:
  mongo:
    container_name: mongo
    image: mongo:4.4.6
    volumes:
      - ./docker-data/mongo:/data/db

  node:
    image: twaketech/twake-node:latest
    ports:
      - 3000:3000
      - 8083:3000
    environment:
      - DEV=production
      - SEARCH_DRIVER=mongodb
      - DB_DRIVER=mongodb
      - PUBSUB_TYPE=local
    volumes:
      - ./configuration/backend-node/production.json:/usr/src/app/config/production.json
      - ./docker-data/documents/:/storage/
    depends_on:
      - mongo
    links:
      - mongo
```

Thank you
